---
# code: language=ansible

- name: All hosts playbook
  ansible.builtin.import_playbook:
    - melissa-playbook.yml
    - bunryl-playbook.yml
    - claudia-playbook.yml
    - helene-playbook.yml
    - giustina-playbook.yml
