---
# code: language=ansible

- name: All rasp's playbook
  hosts:
    - clb_rasp
  roles:
    - role: updates
    - role: deerhide_users
    - role: operator_gpg
    - role: svc_docker
    - role: svc_traefik
    - role: svc_alloy
    - role: svc_portainer_agent
